# my global config
# REF: https://github.com/PagerTree/prometheus-grafana-alertmanager-example/blob/master/prometheus/prometheus.yml
global:
  scrape_interval:     1m # By default, scrape targets every 15 seconds.
  evaluation_interval: 1m # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

remote_write:
- url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
  basic_auth:
    username: [username]
    password: [password]

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
 - job_name: 'chainflip-substrate'
   scrape_interval: 1m
   static_configs:
     - targets: ['chainflip-node:9615']
       labels:
         server: 1.2.3.4
 - job_name: "chainflip-system"
   scrape_interval: 1m
   static_configs:
   - targets: ['cadvisor:8080','node-exporter:9100']
     labels:
       region: test
       type: system
       server: 1.2.3.4
       instance: 1.2.3.4
   metric_relabel_configs:
   - source_labels: [__name__]
     regex: node_cpu_seconds_total|node_boot_time_seconds|node_load(5|15)|node_memory_Mem(Total|Free|Available)_bytes|node_memory_Swap(Total|Free)_bytes|node_memory_Swap(Total|Free)_bytes|node_memory_Swap(Total|Free)_bytes|node_memory_(Cached|Buffers|SReclaimable)_bytes|node_filesystem_(avail|size)_bytes|node_network_(receive|transmit)_bytes_total
     action: keep

